##### 1) Load the Iris dataset as a list of lists (each of the 150 lists should have 5 elements). Compute and print the mean and the standard deviation for each of the 4 measurement columns (i.e. sepal length and width, petal length and width). Compute and print the mean and the standard deviation for each of the 4 measurement columns, separately for each of the three Iris species (Versicolor, Virginica and Setose). Which measurement would you consider “best”, if you were to guess the Iris species based only on those four values? 

In [295]:
import pandas as pd


In [296]:
##drive.mount('/content/drive')

In [297]:
df = pd.read_csv("irisdataset.csv")

In [298]:
df.describe()

Id  sepal_length  sepal_width  petal_length  petal_width
count  150.000000    150.000000   150.000000    150.000000   150.000000
mean    75.500000      5.843333     3.054000      3.758667     1.198667
std     43.445368      0.828066     0.433594      1.764420     0.763161
min      1.000000      4.300000     2.000000      1.000000     0.100000
25%     38.250000      5.100000     2.800000      1.600000     0.300000
50%     75.500000      5.800000     3.000000      4.350000     1.300000
75%    112.750000      6.400000     3.300000      5.100000     1.800000
max    150.000000      7.900000     4.400000      6.900000     2.500000

In [299]:
df.head()

Id  sepal_length  sepal_width  petal_length  petal_width      species
0   1           5.1          3.5           1.4          0.2  Iris-setosa
1   2           4.9          3.0           1.4          0.2  Iris-setosa
2   3           4.7          3.2           1.3          0.2  Iris-setosa
3   4           4.6          3.1           1.5          0.2  Iris-setosa
4   5           5.0          3.6           1.4          0.2  Iris-setosa

In [300]:
#df.shape,df.columns

In [301]:
df["species"].value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: species, dtype: int64

In [302]:
print("sepal_length mean and Deviation is ", df["sepal_length"].mean(),df["sepal_length"].std())


sepal_length mean and Deviation is  5.843333333333334 0.8280661279778629


In [303]:
print("sepal_width mean and Deviation is ", df["sepal_width"].mean(),df["sepal_width"].std())
    

sepal_width mean and Deviation is  3.0540000000000003 0.4335943113621737


In [304]:
print("petal_length mean and Deviation is ", df["petal_length"].mean(),df["petal_length"].std())

petal_length mean and Deviation is  3.758666666666666 1.7644204199522617


In [305]:
print("petal_length mean and Deviation is ", df["petal_width"].mean(),df["petal_width"].std())

petal_length mean and Deviation is  1.1986666666666668 0.7631607417008414


In [306]:
 df[df['species']=="Iris-versicolor"].mean()

C:\Users\Language Lab\AppData\Local\Temp\ipykernel_3944\1808947818.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df[df['species']=="Iris-versicolor"].mean()


Id              75.500
sepal_length     5.936
sepal_width      2.770
petal_length     4.260
petal_width      1.326
dtype: float64

In [307]:
 df[df['species']=="Iris-setosa"].mean()

C:\Users\Language Lab\AppData\Local\Temp\ipykernel_3944\1346809083.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df[df['species']=="Iris-setosa"].mean()


Id              25.500
sepal_length     5.006
sepal_width      3.418
petal_length     1.464
petal_width      0.244
dtype: float64

In [308]:
 df[df['species']=="Iris-virginica"].mean()

C:\Users\Language Lab\AppData\Local\Temp\ipykernel_3944\3146510401.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df[df['species']=="Iris-virginica"].mean()


Id              125.500
sepal_length      6.588
sepal_width       2.974
petal_length      5.552
petal_width       2.026
dtype: float64

# Exp-5 to split data into train and test

In [309]:
#train_data=df.sample(frac=.8)

In [310]:
#train_data["species"].value_counts()

In [311]:
#test_data=df.loc[~df.index.isin(train_data.index)]

In [312]:
#test_data["species"].value_counts()

In [313]:
df1=df.drop("Id",axis=1)

In [314]:
df1.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [315]:
from sklearn.model_selection import train_test_split
train,test= train_test_split(df1,test_size=0.2)

In [316]:
len(train),len(test)

(120, 30)

In [317]:
train.head(10)

sepal_length  sepal_width  petal_length  petal_width          species
102           7.1          3.0           5.9          2.1   Iris-virginica
0             5.1          3.5           1.4          0.2      Iris-setosa
101           5.8          2.7           5.1          1.9   Iris-virginica
42            4.4          3.2           1.3          0.2      Iris-setosa
77            6.7          3.0           5.0          1.7  Iris-versicolor
68            6.2          2.2           4.5          1.5  Iris-versicolor
1             4.9          3.0           1.4          0.2      Iris-setosa
103           6.3          2.9           5.6          1.8   Iris-virginica
6             4.6          3.4           1.4          0.3      Iris-setosa
114           5.8          2.8           5.1          2.4   Iris-virginica

In [318]:
train["species"].value_counts()

Iris-virginica     41
Iris-versicolor    41
Iris-setosa        38
Name: species, dtype: int64

In [319]:
test["species"].value_counts()

Iris-setosa        12
Iris-versicolor     9
Iris-virginica      9
Name: species, dtype: int64

In [321]:
train.to_csv('C:\\Users\\Language Lab\\Iries_train_data.csv',index=False)
test.to_csv('C:\\Users\\Language Lab\\Iries_test_data.csv',index=False)

In [322]:
train_df = pd.read_csv("Iries_train_data.csv")
test_df= pd.read_csv("Iries_test_data.csv")

In [323]:
train_df.head()

sepal_length  sepal_width  petal_length  petal_width          species
0           7.1          3.0           5.9          2.1   Iris-virginica
1           5.1          3.5           1.4          0.2      Iris-setosa
2           5.8          2.7           5.1          1.9   Iris-virginica
3           4.4          3.2           1.3          0.2      Iris-setosa
4           6.7          3.0           5.0          1.7  Iris-versicolor

In [324]:
# how many missing values are there Train data?
train_df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [325]:
#what is the propotion of "sertosa" in test dataset?
sertosa_count=test_df[test_df["species"]=="Iris-setosa"].value_counts().sum()
#print("propotion of sertosa in test dataset", )

## What is the accuracy score of the K-Nearest Neighbor model (model_1) with 2/3 neighbors using Train_Data and Test_Data? 

In [326]:
from sklearn.neighbors import KNeighborsClassifier 
knn=KNeighborsClassifier(n_neighbors=2)

In [327]:
x_train=train_df.drop('species',axis=1)
y_train=train_df["species"]
x_test=test_df.drop('species',axis=1)
y_test=test_df["species"]

In [328]:
x_train.head()

sepal_length  sepal_width  petal_length  petal_width
0           7.1          3.0           5.9          2.1
1           5.1          3.5           1.4          0.2
2           5.8          2.7           5.1          1.9
3           4.4          3.2           1.3          0.2
4           6.7          3.0           5.0          1.7

In [329]:
y_train.head()

0     Iris-virginica
1        Iris-setosa
2     Iris-virginica
3        Iris-setosa
4    Iris-versicolor
Name: species, dtype: object

In [330]:
x_test[:5]

sepal_length  sepal_width  petal_length  petal_width
0           6.1          2.8           4.0          1.3
1           5.4          3.0           4.5          1.5
2           5.9          3.0           4.2          1.5
3           5.8          2.7           5.1          1.9
4           5.9          3.0           5.1          1.8

In [332]:
knn.fit(x_train,y_train)# training phase 

KNeighborsClassifier(n_neighbors=2)

In [335]:
score=knn.score(x_test,y_test)
score

0.9333333333333333

In [336]:
from sklearn.impute import SimpleImputer

# Create an imputer object
imputer = SimpleImputer(strategy='mean')

# Fit and transform your training data
x_train_imputed = imputer.fit_transform(x_train)

# Transform your test data using the same imputer
x_test_imputed = imputer.transform(x_test)

# Now you can use x_train_imputed and x_test_imputed for prediction
pred = knn.predict(x_test_imputed)
# Drop rows with missing values
x_train_cleaned = x_train.dropna()
x_test_cleaned = x_test.dropna()

# Now you can use x_train_cleaned and x_test_cleaned for prediction
pred = knn.predict(x_test_cleaned)


pred=knn.predict(x_test)
pred

C:\Users\Language Lab\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array(['Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa'], dtype=object)

In [337]:
y_test

0     Iris-versicolor
1     Iris-versicolor
2     Iris-versicolor
3      Iris-virginica
4      Iris-virginica
5         Iris-setosa
6         Iris-setosa
7         Iris-setosa
8     Iris-versicolor
9         Iris-setosa
10     Iris-virginica
11    Iris-versicolor
12     Iris-virginica
13     Iris-virginica
14     Iris-virginica
15     Iris-virginica
16    Iris-versicolor
17    Iris-versicolor
18     Iris-virginica
19        Iris-setosa
20        Iris-setosa
21        Iris-setosa
22        Iris-setosa
23        Iris-setosa
24        Iris-setosa
25    Iris-versicolor
26        Iris-setosa
27    Iris-versicolor
28     Iris-virginica
29        Iris-setosa
Name: species, dtype: object

In [338]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [339]:
print(confusion_matrix(y_test,pred))

[[12  0  0]
 [ 0  8  1]
 [ 0  1  8]]


In [340]:
print(classification_report(y_test,pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       0.89      0.89      0.89         9
 Iris-virginica       0.89      0.89      0.89         9

       accuracy                           0.93        30
      macro avg       0.93      0.93      0.93        30
   weighted avg       0.93      0.93      0.93        30



## Build a logistic regression model (model_2) keeping the modelling steps constant. Find the accuracy of the model_2 

In [341]:
from sklearn.linear_model import LogisticRegression

In [342]:
model2=LogisticRegression()

In [343]:
model2.fit(x_train,y_train)

C:\Users\Language Lab\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [344]:
pred=model2.predict(x_test)

In [345]:
pred

array(['Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa'], dtype=object)

In [346]:
accuracy_score(y_test,pred)

1.0

In [347]:
confusion_matrix(y_test,pred)

array([[12,  0,  0],
       [ 0,  9,  0],
       [ 0,  0,  9]], dtype=int64)

In [348]:
print(classification_report(y_test,pred))


                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00         9

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30



## Exp-7 :Demonstrate Decision tree classification model and Evaluate the performance of classifier on Iris

In [349]:
from sklearn.tree import DecisionTreeClassifier

In [350]:
clf=DecisionTreeClassifier(max_depth=3,random_state=42)

In [351]:
clf.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=3, random_state=42)

In [352]:
pred=clf.predict(x_test)
pred

array(['Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa'], dtype=object)

In [353]:
confusion_matrix(y_test,pred)

array([[12,  0,  0],
       [ 0,  9,  0],
       [ 0,  0,  9]], dtype=int64)

In [354]:
accuracy_score(y_test,pred)

1.0

In [355]:
print(classification_report(y_test,pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00         9

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30



# Demonstrate any of the Clustering model and Evaluate the performance on Iris dataset. 

In [356]:
from sklearn.cluster import KMeans

In [357]:
km=KMeans(n_clusters=3)

In [358]:
km.fit(x_train,y_train)

C:\Users\Language Lab\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
C:\Users\Language Lab\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


KMeans(n_clusters=3)

In [359]:
km.labels_[:10]

array([2, 0, 1, 0, 2, 1, 0, 2, 0, 1])

In [360]:
pred=km.predict(x_test)

In [361]:
pred[:10]

array([1, 1, 1, 1, 1, 0, 0, 0, 1, 0])

In [362]:
km.cluster_centers_

array([[5.01842105, 3.41842105, 1.48157895, 0.25      ],
       [5.94489796, 2.75102041, 4.38163265, 1.42857143],
       [6.88181818, 3.07878788, 5.74848485, 2.08181818]])

In [363]:
y_test

0     Iris-versicolor
1     Iris-versicolor
2     Iris-versicolor
3      Iris-virginica
4      Iris-virginica
5         Iris-setosa
6         Iris-setosa
7         Iris-setosa
8     Iris-versicolor
9         Iris-setosa
10     Iris-virginica
11    Iris-versicolor
12     Iris-virginica
13     Iris-virginica
14     Iris-virginica
15     Iris-virginica
16    Iris-versicolor
17    Iris-versicolor
18     Iris-virginica
19        Iris-setosa
20        Iris-setosa
21        Iris-setosa
22        Iris-setosa
23        Iris-setosa
24        Iris-setosa
25    Iris-versicolor
26        Iris-setosa
27    Iris-versicolor
28     Iris-virginica
29        Iris-setosa
Name: species, dtype: object

In [364]:
from sklearn import datasets

In [365]:
iris=datasets.load_iris()

In [366]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [367]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [368]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [369]:
km=KMeans(n_clusters=3)

In [370]:
km.fit(iris.data,iris.target)

C:\Users\Language Lab\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
C:\Users\Language Lab\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


KMeans(n_clusters=3)

In [371]:
km.cluster_centers_

array([[6.85      , 3.07368421, 5.74210526, 2.07105263],
       [5.006     , 3.428     , 1.462     , 0.246     ],
       [5.9016129 , 2.7483871 , 4.39354839, 1.43387097]])

In [372]:
km.labels_

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0,
       0, 0, 0, 2, 2, 0, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 2, 2, 0, 0, 0, 0,
       0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 2])

In [373]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [374]:
import numpy as np


In [375]:
pred=np.choose(km.labels_,[1,0,2]).astype(np.int64)

In [376]:
confusion_matrix(pred,iris.target)

array([[50,  0,  0],
       [ 0,  2, 36],
       [ 0, 48, 14]], dtype=int64)

In [378]:
accuracy_score(iris.target,pred)

0.44